### ISSUE TITLE
User Friendly improvement checklist.

### ISSUE THREAD

**Issue by ryantheleach** [MinecraftPortCentral/GriefPrevention#33]
This was performed on hunterz test server, Unsure if it's a result of possible permissions missing.

If a case of missing permissions, some system of default permissions should be used, probably using PermissionDescriptions if supported by the PermissionsService.
- [ ] Commands should give helpful messages or prompt, guessing what the player might want next.
  ![image](https://cloud.githubusercontent.com/assets/141554/14668513/dc5f2f32-0723-11e6-97e2-f62a95ab4af7.png)
- [ ] Tab completion only completes so far. makes it impossible to guess what the command wants.
  ![image](https://cloud.githubusercontent.com/assets/141554/14668557/28946a52-0724-11e6-9082-3aab1caa1e56.png)
- [ ] Whilst /gp help may be descriptive (I currently can't test, don't have permission) /help gp and /help GriefPrevention isn't very useful at all. Consider adding better support for the default help system, as it's likely what users will turn to first due to familiarity with sponge/bukkit.

![image](https://cloud.githubusercontent.com/assets/141554/14668710/be53ab84-0724-11e6-8553-d384986d5f6c.png)

**Comment by bloodmc** [comment]
@ryantheleach I've added original /slash commands from bukkit so this should be more user friendly to the end user. The '/gp' command definitely could use some work.

**Comment by bloodmc** [comment]
Latest build no longer uses the /gp command and all commands support tabbing.
